### ISSUE TITLE
Add link to documentation to CU-Robosub account/organization page

### ISSUE THREAD

**Issue by Will-Shanks** [CU-Robosub/cusub_documentation#6]
A link to the read the docs should be put somewhere obvious so one does not need to already know the URL to find it. On the top of the CU-Robosub page next to the club email and CU webpage could be good, or in the readme for the cusub_* repos

**Comment by belgiumkansas** [comment]
I don't want to put it on the website (I want our documentation to be semi internal) but I can put it within the github wiki and make it private to our organization. Aka if someone wants to join the software team they actually have to come to a meeting to get accepted to our org and slack and all that good stuff

**Comment by Will-Shanks** [comment]
I don't think it matters where the link is put, but it should be easy to move from the code to the relevant docs, and vice versa
